#pdf(file="graunt.pdf",width=6,height=6)
png(file="graunt.png",width=480,height=480)
par(family="Korea1deb")
graunt.x<-c(graunt$x,rev(graunt$x))
graunt.y<-c(rep(0,length(graunt$x)),rev(graunt$lx))
plot(graunt$x,graunt$lx,xlab="",ylab="",type="l")
#abline(v=c(0,76),lty=2)
abline(v=graunt$x,lty=2)
polygon(graunt.x,graunt.y,density=15)
title(main="John Graunt의 생존 곡선", xlab="연령(세)", ylab="생존률(%)")
dev.off()
