par(family="Korea1deb")
#pdf("life-distribution-1.pdf",width=6,height=6)
#pdf("life-distribution-2.pdf",width=6,height=6)
#png("life-distribution-1.png",width=480,height=480)
png("life-distribution-3.png",width=480,height=480)
plot(lt.kor.simple$age,lt.kor.simple[,2]/100000,xlab="",ylab="",type="l")
lines(lt.kor.simple$age,lt.kor.simple[,3]/100000,xlab="",ylab="")
lines(lt.kor.simple$age,lt.kor.simple[,4]/100000,xlab="",ylab="")
lines(lt.kor.simple$age,lt.kor.simple[,5]/100000,xlab="",ylab="")
lines(lt.kor.simple$age,lt.kor.simple[,6]/100000,xlab="",ylab="")
#x<-c(lifetable.kr$age,rev(lifetable.kr$age))
#y<-c(lifetable.kr$lx.m/1000,rev(lifetable.kr$lx.f/1000))
#polygon(x,y,border=NA,density=15)
#legend(80,100,legend=c("남","여"),col=c("blue","red"),lty=1)
title(main="국민생존함수의 변화",xlab="연령(세)",ylab="생존률(%)")
dev.off()
